package com.springmvc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jan 10, 2020 11:43:09 PM by Hibernate Tools 5.4.7.Final

/**
 * Chitietdonhang generated by hbm2java
 */
@Entity
@Table(name="chitietssanpham")
public class Chitietdonhang implements java.io.Serializable {

	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name="soluong")
	private Integer soLuong;
	
	@Column(name="dongia")
	private Float donGia;
	
	@Column(name="thanhtien")
	private Float thanhTien;
	
	@Column(name="masp")
	private Long maSp;
	
	@Column(name="madh")
	private Long maDh;

	public Chitietdonhang() {
	}

	public Chitietdonhang(Integer soLuong, Float donGia, Float thanhTien, Long maSp, Long maDh) {
		this.soLuong = soLuong;
		this.donGia = donGia;
		this.thanhTien = thanhTien;
		this.maSp = maSp;
		this.maDh = maDh;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	public Float getDonGia() {
		return this.donGia;
	}

	public void setDonGia(Float donGia) {
		this.donGia = donGia;
	}

	public Float getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(Float thanhTien) {
		this.thanhTien = thanhTien;
	}

	public Long getMaSp() {
		return this.maSp;
	}

	public void setMaSp(Long maSp) {
		this.maSp = maSp;
	}

	public Long getMaDh() {
		return this.maDh;
	}

	public void setMaDh(Long maDh) {
		this.maDh = maDh;
	}

}
