package com.springmvc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jan 10, 2020 11:43:09 PM by Hibernate Tools 5.4.7.Final

/**
 * Danhmucsp generated by hbm2java
 */
@Entity
@Table(name = "danhmucsp")
public class Danhmucsp implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name ="name")
	private String name;
	
	@Column(name="hoatdong")
	private Boolean hoatDong;

	public Danhmucsp() {
	}

	public Danhmucsp(String name, Boolean hoatDong) {
		this.name = name;
		this.hoatDong = hoatDong;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getHoatDong() {
		return this.hoatDong;
	}

	public void setHoatDong(Boolean hoatDong) {
		this.hoatDong = hoatDong;
	}

}
