package com.springmvc.entity;
// Generated Jan 10, 2020 11:43:09 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Donhang generated by hbm2java
 */
@Entity
@Table(name = "donhang")
public class Donhang implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "makh")
	private Long maKh;
	
	@Column(name = "thanhtien")
	private Float thanhTien;
	
	@Column(name = "trangthai")
	private Boolean trangThai;
	
	@Column(name = "ngaylap")
	private Date ngayLap;
	
	@Column(name = "ngaygiao")
	private Date ngayGiao;

	public Donhang() {
	}

	public Donhang(Long maKh, Float thanhTien, Boolean trangThai, Date ngayLap, Date ngayGiao) {
		this.maKh = maKh;
		this.thanhTien = thanhTien;
		this.trangThai = trangThai;
		this.ngayLap = ngayLap;
		this.ngayGiao = ngayGiao;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getMaKh() {
		return this.maKh;
	}

	public void setMaKh(Long maKh) {
		this.maKh = maKh;
	}

	public Float getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(Float thanhTien) {
		this.thanhTien = thanhTien;
	}

	public Boolean getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Boolean trangThai) {
		this.trangThai = trangThai;
	}

	public Date getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(Date ngayLap) {
		this.ngayLap = ngayLap;
	}

	public Date getNgayGiao() {
		return this.ngayGiao;
	}

	public void setNgayGiao(Date ngayGiao) {
		this.ngayGiao = ngayGiao;
	}

}
