package com.springmvc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


// Generated Jan 10, 2020 11:43:09 PM by Hibernate Tools 5.4.7.Final

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name = "sanpham")
public class Sanpham implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(name="tensp")
	private String tenSp;
	
	@Column(name ="gia")
	private Float gia;
	
	@Column(name = "dvt")
	private String dvt;
	
	@Column(name="hinhanh")
	private String hinhAnh;
	
	@Column(name = "mota")
	private String mota;
	
	@Column(name = "giakhuyenmai")
	private Float giaKhuyenMai;
	
	@Column(name = "soluong")
	private Long soLuong;
	
	@Column(name= "loaisp")
	private String loaiSp;
	
	@Column(name = "hoatdong")
	private Boolean hoatDong;
	
	@Column(name ="spnoibat")
	private Boolean spnoiBat;
	
	@Column(name="spbanchay")
	private Boolean spbanChay;

	public Sanpham() {
	}

	public Sanpham(String tenSp, Float gia, String dvt, String hinhAnh, String mota, Float giaKhuyenMai, Long soLuong,
			String loaiSp, Boolean hoatDong, Boolean spnoiBat, Boolean spbanChay) {
		this.tenSp = tenSp;
		this.gia = gia;
		this.dvt = dvt;
		this.hinhAnh = hinhAnh;
		this.mota = mota;
		this.giaKhuyenMai = giaKhuyenMai;
		this.soLuong = soLuong;
		this.loaiSp = loaiSp;
		this.hoatDong = hoatDong;
		this.spnoiBat = spnoiBat;
		this.spbanChay = spbanChay;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTenSp() {
		return this.tenSp;
	}

	public void setTenSp(String tenSp) {
		this.tenSp = tenSp;
	}

	public Float getGia() {
		return this.gia;
	}

	public void setGia(Float gia) {
		this.gia = gia;
	}

	public String getDvt() {
		return this.dvt;
	}

	public void setDvt(String dvt) {
		this.dvt = dvt;
	}

	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	public Float getGiaKhuyenMai() {
		return this.giaKhuyenMai;
	}

	public void setGiaKhuyenMai(Float giaKhuyenMai) {
		this.giaKhuyenMai = giaKhuyenMai;
	}

	public Long getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Long soLuong) {
		this.soLuong = soLuong;
	}

	public String getLoaiSp() {
		return this.loaiSp;
	}

	public void setLoaiSp(String loaiSp) {
		this.loaiSp = loaiSp;
	}

	public Boolean getHoatDong() {
		return this.hoatDong;
	}

	public void setHoatDong(Boolean hoatDong) {
		this.hoatDong = hoatDong;
	}

	public Boolean getSpnoiBat() {
		return this.spnoiBat;
	}

	public void setSpnoiBat(Boolean spnoiBat) {
		this.spnoiBat = spnoiBat;
	}

	public Boolean getSpbanChay() {
		return this.spbanChay;
	}

	public void setSpbanChay(Boolean spbanChay) {
		this.spbanChay = spbanChay;
	}

}
